# User credentials
username: "SCN_ADMIN"
password: "Welcome123!"

#servername
servername: "fa-epyt-test-saasfaprod1.fa.ocs.oraclecloud.com" #enter the main URL part of the environment

#IDs of ODMC profile,pla,accuracy table, top offenders table
profile_id: "300000015730132"
plan_id: "300000015838445"  #32->TX - SYK Dem Plan - JR - copy4
accuracy_table_id: "300000015925166"  #@TX Y - Tuning Table
top_offenders_table_id: "300000049968289"
year_over_year_table_id: "300000050001375" #@TX Y - Yoy
CF_kinds_table_id: "300000049968529" #@TX Y - Kinds
#Other Parameters
Number_of_top_offenders: 3 #enter the number of top offenders to find


Kind Values:
  - 1
  - 2
  - 800


Tune_by_step: "Off"
#Forecasting Parameters
parameters:
  FitValidationSensitivity:
    - 0.5
  #  - 1
  #  - 1.7
  #  - 2
  #ForecastValidationSensitivity:
  #  - 3.5
  #  - 4.5
  #  - 5
  #OutlierSensitivity:
  #  - 1
  # - 2
  #  - 3
  #OutliersPercent:
    # 20
    #- 5
    # 10
  #EnableNonNegRegr:
  #  - 1
  
parameters by step:
  - name: OutlierSensitivity
    min: 1
    max: 2
    step: 0.2
  - name: OutliersPercent
    min: 5
    max: 5
    step: 25

Tune_by_wmape: "On" #if "On", the best value of each paramter (the one that yields the best WMAPE) will be choosen and used for the next run. if "Off" - values will be reset after each parameter run 
Base_WMAPE: 15.26
Base_Bias: -3.36
Parameters_tuning_mode: "Regular" #options: "Regular" or "Cartesian"


Configure best kind IDs on ODMC: "Off" #could be "On" or "Off"
run_mode: "Dummy" #"Dummy" / "Parameters" / "CFs" / "Parameters then CFs" / "CFs then Parameters"